---
version: "3.5"

services:
  isitcamp_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: isitcamp-api:local
    container_name: isitcamp_api
    command: bash -c "npm run build && npm start"
    environment:
      - DEBUG=true
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
  isitcamp_dev_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: isitcamp-dev-server:local
    container_name: isitcamp_dev_server
    command: bash -c "npm run build && npm run client-dev"
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
  isitcamp_reverse_proxy:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    image: isitcamp-reverse-proxy
    container_name: isitcamp_reverse_proxy
    ports:
      - 80:80
