---
version: "3.5"

services:
  mongodb:
    image: mongo:3.4
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: isitcamp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongo-volume:/data/db
    ports:
      - 27017-27019:27017-27019
  isitcamp_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: isitcamp_api:local
    container_name: isitcamp_api
    command: bash -c "npm run build && npm start"
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
  isitcamp_dev_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: isitcamp_dev_server:local
    container_name: isitcamp_dev_server
    command: bash -c "npm run client-dev"
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
